version: "3"

services:
  namenode:
    container_name: namenode
    hostname: namenode
    build:
      context: .
      dockerfile: ./hadoop_containers_config/namenode/Dockerfile
    ports:
      - 9870:9870
      - 8020:8020
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: /tmp/hadoop-root/dfs/name
    command: ["hdfs", "namenode"]

  datanode:
    container_name: datanode
    build:
      context: .
      dockerfile: ./hadoop_containers_config/Dockerfile
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    environment:
      ENSURE_DATANODE_DIR: /tmp/hadoop-root/dfs/data
    ports:
      - 9864:9864

  datanode_2:
    container_name: datanode_2
    build:
      context: .
      dockerfile: ./hadoop_containers_config/Dockerfile
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    ports:
      - 9865:9864

  datanode_3:
    container_name: datanode_3
    build:
      context: .
      dockerfile: ./hadoop_containers_config/Dockerfile
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    ports:
      - 9866:9864

  resourcemanager:
    build:
      context: .
      dockerfile: ./hadoop_containers_config/Dockerfile
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
      - 8042:8042
    env_file:
      - ./config

  nodemanager:
    build:
      context: .
      dockerfile: ./hadoop_containers_config/Dockerfile
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config

  nodemanager_2:
    build:
      context: .
      dockerfile: ./hadoop_containers_config/Dockerfile
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config

  nodemanager_3:
    build:
      context: .
      dockerfile: ./hadoop_containers_config/Dockerfile
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config

  historyserver:
    build:
      context: .
      dockerfile: ./hadoop_containers_config/Dockerfile
    command: ["mapred", "historyserver"]
    ports:
      - 19888:19888
    env_file:
      - ./config
